name: Release File

on:
  push:
    tags:
    - 'v*'

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        arch: [x64]

    runs-on: ${{ matrix.os }}-latest 
    
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: dotnet publish -p:PublishProfile=${{ matrix.os }}-${{ matrix.arch }}

    - name: Create Release Unix
      uses: fnkr/github-action-ghr@v1
      if: matrix.os != 'windows' && startsWith(github.ref, 'refs/tags/')
      env:
          GHR_COMPRESS: xz
          GHR_PATH: bin/Release/net8.0/publish/${{ matrix.os }}-${{ matrix.arch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Create Release Win
      uses: fnkr/github-action-ghr@v1
      if: matrix.os == 'windows' && startsWith(github.ref, 'refs/tags/')
      env:
          GHR_COMPRESS: zip
          GHR_PATH: bin/Release/net8.0/publish/${{ matrix.os }}-${{ matrix.arch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}