name: Release File

on:
  push:
    tags:
    - 'v*'

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        arch: [x64]

    runs-on: ${{ matrix.os }}-latest 

    permissions:
      contents: write
    
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: cd SPRView.Net && dotnet publish -p:PublishProfile=${{ matrix.os }}-${{ matrix.arch }}

    - name: Zipping All
      if: matrix.os == 'windows'
      uses: vimtor/action-zip@v1
      with:
          files: bin/Release/net8.0/publish/${{ matrix.os }}-${{ matrix.arch }}
          dest: SPRView.Net-${{ matrix.os }}-${{ matrix.arch }}.zip

    - name: Tarball All
      if: matrix.os != 'windows'
      run: tar -czvf ./SPRView.Net-${{ matrix.os }}-${{ matrix.arch }}.tar.gz ./bin/Release/net8.0/publish/${{ matrix.os }}-${{ matrix.arch }}

    - name: Create Release Unix
      if: matrix.os != 'windows' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
          name: SPRView.Net-${{ github.ref }}
          files: |
            ./SPRView.Net-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

    - name: Create Release Win
      if: matrix.os == 'windows' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
          name: SPRView.Net-${{ github.ref }}
          files: |
            SPRView.Net-${{ matrix.os }}-${{ matrix.arch }}.zip
