name: Release File

on:
  push:
    tags:
    - 'v*'

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        arch: [arm, x64, x86]

    runs-on: ${{ matrix.os }}-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Publish
      run: dotnet publish -p:PublishProfile=${{ matrix.os }}-${{ matrix.arch }}

    - name: Zipping All
      if: mtrix.os == 'windows'
      uses: vimtor/action-zip@v1
      with:
          files: bin\Release\net8.0\publish\${{ matrix.os }}-${{ matrix.arch }}
          dest: SPRView.Net-${{ matrix.os }}-${{ matrix.arch }}.zip

    - name: Tarball All
      if: mtrix.os != 'windows'
      run: tar -czvf SPRView.Net-${{ matrix.os }}-${{ matrix.arch }}.tar.gz bin\Release\net8.0\publish\${{ matrix.os }}-${{ matrix.arch }}

    - name: Create Release Unix
      if: mtrix.os == 'windows' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
          name: SPRView.Net-${{ github.ref }}
          files: |
            SPRView.Net-${{ matrix.os }}-${{ matrix.arch }}.zip

    - name: Create Release Win
      if: mtrix.os != 'windows' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
          name: SPRView.Net-${{ github.ref }}
          files: |
            SPRView.Net-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
